import "./globals.css";

export const metadata = {
  title: "Country Facts",
  // description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <html lang="en">
      <body className="p-6">
        <header></header>
        {children}
        <footer></footer>
      </body>
    </html>
  );
}
