import "./globals.css";

export const metadata = {
  title: "Country Facts",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="p-7">{children}</body>
    </html>
  );
}
